import { createTask, listTasks } from "../../../lib/tasks.ts";
import type { CreateTaskInput } from "../../../types/task.ts";

export async function GET() {
  try {
    return Response.json(await listTasks(), { status: 200 });
  } catch {
    return Response.json({ error: "Unable to fetch tasks." }, { status: 500 });
  }
}

export async function POST(request: Request) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  if (typeof body !== "object" || body === null || Array.isArray(body)) {
    return Response.json({ error: "Expected a JSON object." }, { status: 400 });
  }

  const { title, description, priority, due_date } = body as Record<string, unknown>;

  if (typeof title !== "string" || !title.trim() || title.trim().length > 200) {
    return Response.json(
      { error: "Title must contain between 1 and 200 characters." },
      { status: 400 },
    );
  }

  if (
    description !== undefined &&
    description !== null &&
    (typeof description !== "string" || description.length > 10000)
  ) {
    return Response.json(
      { error: "Description must be a string of at most 10000 characters or null." },
      { status: 400 },
    );
  }

  if (
    priority !== undefined &&
    priority !== "low" && priority !== "medium" && priority !== "high"
  ) {
    return Response.json(
      { error: "Priority must be low, medium, or high." },
      { status: 400 },
    );
  }

  if (due_date !== undefined && due_date !== null) {
    const parsed = typeof due_date === "string" ? new Date(due_date) : null;
    if (
      typeof due_date !== "string" ||
      !/^\d{4}-\d{2}-\d{2}$/.test(due_date) ||
      !parsed || !Number.isFinite(parsed.getTime()) ||
      parsed.toISOString().slice(0, 10) !== due_date
    ) {
      return Response.json(
        { error: "Due date must be a valid YYYY-MM-DD date or null." },
        { status: 400 },
      );
    }
  }

  // Build an allowlisted payload; IDs and timestamps are generated by the database.
  const input: CreateTaskInput = {
    title: title.trim(),
    description: typeof description === "string" ? description.trim() : null,
    priority: priority ?? "medium",
    due_date: typeof due_date === "string" ? due_date : null,
    completed: false,
  };

  try {
    return Response.json(await createTask(input), { status: 201 });
  } catch {
    return Response.json({ error: "Unable to create task." }, { status: 500 });
  }
}
